### ISSUE TITLE
Another  vulnerabilitie

### ISSUE THREAD

**Issue by samuelhavefun** [PentesterLab/cr#1]
classes/user.php 
 public static function register($user, $password) {
    $sql = "INSERT INTO  users (login,password) values (\"";
    $sql.= mysql_real_escape_string($user);
    $sql.= "\", md5(\"";
    $sql.= mysql_real_escape_string($password);
    $sql.= "\"))";
    $result = mysql_query($sql);
    if ($result) {
      return TRUE;
    }
    else 
      echo mysql_error();
    return FALSE;
    //die("invalid username/password");
  }
}

The application uses 'echo mysql_error()' to show errors, but if we register a username which already exists in
the database, we can trigger a XSS using username like samuel<script>alert(1)</script>.

**Comment by samuelhavefun** [comment]
and I think as for The Authentication bypass, we can just create a malicious user named 'admin,'

**Comment by snyff** [comment]
Yes, agree on both. The json parsing is built like that for this reason.

Louis

**Comment by snyff** [comment]
I added more details on the mysql_error one in the course
