### ISSUE TITLE
An extra Forward Slash

### ISSUE THREAD

**Issue by wisahmed** [PentesterLab/cr#2]
I'm not sure if its an issue.

But I had to remove all the '/' in header() and 'href=' for the application to load the pages.
I use XAMPP to host these files. 

With '/' it directly went to my htdocs folder, whereas, I had put all these files within a folder inside htdocs.

Cheers,
WISAHMED

**Comment by snyff** [comment]
Hi,

The application is not supposed to be installed nor used. The goal is to review the source code.

Cheers,
